<?php
/**
 * CreateJobs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Misterbabel API
 *
 * Welcome to the Misterbabel API documentation. Here you'll find details about our API.<br><br>If you have any problems or request please contact our support team.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@powerling.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * CreateJobs Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateJobs implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Create jobs';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'type' => 'string',
        'title' => 'string',
        'custom_reference' => 'string',
        'lc_source' => 'string',
        'lc_target' => 'string',
        'comment' => 'string',
        'file_url_source' => 'string',
        'callback_url' => 'string',
        'review' => 'bool',
        'domain' => 'int',
        'text_type' => 'int',
        'reference_doc_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'type' => null,
        'title' => null,
        'custom_reference' => null,
        'lc_source' => null,
        'lc_target' => null,
        'comment' => null,
        'file_url_source' => null,
        'callback_url' => null,
        'review' => null,
        'domain' => null,
        'text_type' => null,
        'reference_doc_url' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'title' => 'title',
        'custom_reference' => 'custom_reference',
        'lc_source' => 'lc_source',
        'lc_target' => 'lc_target',
        'comment' => 'comment',
        'file_url_source' => 'file_url_source',
        'callback_url' => 'callback_url',
        'review' => 'review',
        'domain' => 'domain',
        'text_type' => 'text_type',
        'reference_doc_url' => 'reference_doc_url'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'title' => 'setTitle',
        'custom_reference' => 'setCustomReference',
        'lc_source' => 'setLcSource',
        'lc_target' => 'setLcTarget',
        'comment' => 'setComment',
        'file_url_source' => 'setFileUrlSource',
        'callback_url' => 'setCallbackUrl',
        'review' => 'setReview',
        'domain' => 'setDomain',
        'text_type' => 'setTextType',
        'reference_doc_url' => 'setReferenceDocUrl'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'title' => 'getTitle',
        'custom_reference' => 'getCustomReference',
        'lc_source' => 'getLcSource',
        'lc_target' => 'getLcTarget',
        'comment' => 'getComment',
        'file_url_source' => 'getFileUrlSource',
        'callback_url' => 'getCallbackUrl',
        'review' => 'getReview',
        'domain' => 'getDomain',
        'text_type' => 'getTextType',
        'reference_doc_url' => 'getReferenceDocUrl'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const TYPE_XML = 'xml';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_XML,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['custom_reference'] = isset($data['custom_reference']) ? $data['custom_reference'] : null;
        $this->container['lc_source'] = isset($data['lc_source']) ? $data['lc_source'] : null;
        $this->container['lc_target'] = isset($data['lc_target']) ? $data['lc_target'] : null;
        $this->container['comment'] = isset($data['comment']) ? $data['comment'] : null;
        $this->container['file_url_source'] = isset($data['file_url_source']) ? $data['file_url_source'] : null;
        $this->container['callback_url'] = isset($data['callback_url']) ? $data['callback_url'] : null;
        $this->container['review'] = isset($data['review']) ? $data['review'] : null;
        $this->container['domain'] = isset($data['domain']) ? $data['domain'] : null;
        $this->container['text_type'] = isset($data['text_type']) ? $data['text_type'] : null;
        $this->container['reference_doc_url'] = isset($data['reference_doc_url']) ? $data['reference_doc_url'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['type'] === null) {
            $invalid_properties[] = "'type' can't be null";
        }
        $allowed_values = $this->getTypeAllowableValues();
        if (!in_array($this->container['type'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        if ($this->container['title'] === null) {
            $invalid_properties[] = "'title' can't be null";
        }
        if ($this->container['custom_reference'] === null) {
            $invalid_properties[] = "'custom_reference' can't be null";
        }
        if ($this->container['lc_source'] === null) {
            $invalid_properties[] = "'lc_source' can't be null";
        }
        if ($this->container['lc_target'] === null) {
            $invalid_properties[] = "'lc_target' can't be null";
        }
        if ($this->container['comment'] === null) {
            $invalid_properties[] = "'comment' can't be null";
        }
        if ($this->container['file_url_source'] === null) {
            $invalid_properties[] = "'file_url_source' can't be null";
        }
        if ($this->container['callback_url'] === null) {
            $invalid_properties[] = "'callback_url' can't be null";
        }
        if ($this->container['review'] === null) {
            $invalid_properties[] = "'review' can't be null";
        }
        if ($this->container['domain'] === null) {
            $invalid_properties[] = "'domain' can't be null";
        }
        if ($this->container['text_type'] === null) {
            $invalid_properties[] = "'text_type' can't be null";
        }
        if ($this->container['reference_doc_url'] === null) {
            $invalid_properties[] = "'reference_doc_url' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['type'] === null) {
            return false;
        }
        $allowed_values = $this->getTypeAllowableValues();
        if (!in_array($this->container['type'], $allowed_values)) {
            return false;
        }
        if ($this->container['title'] === null) {
            return false;
        }
        if ($this->container['custom_reference'] === null) {
            return false;
        }
        if ($this->container['lc_source'] === null) {
            return false;
        }
        if ($this->container['lc_target'] === null) {
            return false;
        }
        if ($this->container['comment'] === null) {
            return false;
        }
        if ($this->container['file_url_source'] === null) {
            return false;
        }
        if ($this->container['callback_url'] === null) {
            return false;
        }
        if ($this->container['review'] === null) {
            return false;
        }
        if ($this->container['domain'] === null) {
            return false;
        }
        if ($this->container['text_type'] === null) {
            return false;
        }
        if ($this->container['reference_doc_url'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     * @param string $type
     * @return $this
     */
    public function setType($type)
    {
        $allowed_values = $this->getTypeAllowableValues();
        if (!in_array($type, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets title
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     * @param string $title
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets custom_reference
     * @return string
     */
    public function getCustomReference()
    {
        return $this->container['custom_reference'];
    }

    /**
     * Sets custom_reference
     * @param string $custom_reference Your custom reference
     * @return $this
     */
    public function setCustomReference($custom_reference)
    {
        $this->container['custom_reference'] = $custom_reference;

        return $this;
    }

    /**
     * Gets lc_source
     * @return string
     */
    public function getLcSource()
    {
        return $this->container['lc_source'];
    }

    /**
     * Sets lc_source
     * @param string $lc_source Language code of the source text
     * @return $this
     */
    public function setLcSource($lc_source)
    {
        $this->container['lc_source'] = $lc_source;

        return $this;
    }

    /**
     * Gets lc_target
     * @return string
     */
    public function getLcTarget()
    {
        return $this->container['lc_target'];
    }

    /**
     * Sets lc_target
     * @param string $lc_target Language code of the target text
     * @return $this
     */
    public function setLcTarget($lc_target)
    {
        $this->container['lc_target'] = $lc_target;

        return $this;
    }

    /**
     * Gets comment
     * @return string
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     * @param string $comment The comment of your job, which will be visible to the translator
     * @return $this
     */
    public function setComment($comment)
    {
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets file_url_source
     * @return string
     */
    public function getFileUrlSource()
    {
        return $this->container['file_url_source'];
    }

    /**
     * Sets file_url_source
     * @param string $file_url_source The file you want to translate, it must be in xml format.
     * @return $this
     */
    public function setFileUrlSource($file_url_source)
    {
        $this->container['file_url_source'] = $file_url_source;

        return $this;
    }

    /**
     * Gets callback_url
     * @return string
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     * @param string $callback_url The URL we will use to transmit your translation automatically
     * @return $this
     */
    public function setCallbackUrl($callback_url)
    {
        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets review
     * @return bool
     */
    public function getReview()
    {
        return $this->container['review'];
    }

    /**
     * Sets review
     * @param bool $review Specify if the translation should be verified by another translator
     * @return $this
     */
    public function setReview($review)
    {
        $this->container['review'] = $review;

        return $this;
    }

    /**
     * Gets domain
     * @return int
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     * @param int $domain
     * @return $this
     */
    public function setDomain($domain)
    {
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets text_type
     * @return int
     */
    public function getTextType()
    {
        return $this->container['text_type'];
    }

    /**
     * Sets text_type
     * @param int $text_type
     * @return $this
     */
    public function setTextType($text_type)
    {
        $this->container['text_type'] = $text_type;

        return $this;
    }

    /**
     * Gets reference_doc_url
     * @return string
     */
    public function getReferenceDocUrl()
    {
        return $this->container['reference_doc_url'];
    }

    /**
     * Sets reference_doc_url
     * @param string $reference_doc_url
     * @return $this
     */
    public function setReferenceDocUrl($reference_doc_url)
    {
        $this->container['reference_doc_url'] = $reference_doc_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


