<?php
/**
 * JobGetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Misterbabel API
 *
 * Welcome to the Misterbabel API documentation. Here you'll find details about our API.<br><br>If you have any problems or request please contact our support team.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@powerling.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * JobGetTest Class Doc Comment
 *
 * @category    Class */
// * @description JobGet
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JobGetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JobGet"
     */
    public function testJobGet()
    {
    }

    /**
     * Test attribute "job_id"
     */
    public function testPropertyJobId()
    {
    }

    /**
     * Test attribute "job_reference"
     */
    public function testPropertyJobReference()
    {
    }

    /**
     * Test attribute "custom_reference"
     */
    public function testPropertyCustomReference()
    {
    }

    /**
     * Test attribute "lc_source"
     */
    public function testPropertyLcSource()
    {
    }

    /**
     * Test attribute "lc_target"
     */
    public function testPropertyLcTarget()
    {
    }

    /**
     * Test attribute "creation_time"
     */
    public function testPropertyCreationTime()
    {
    }

    /**
     * Test attribute "delivery_time"
     */
    public function testPropertyDeliveryTime()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "word_count"
     */
    public function testPropertyWordCount()
    {
    }

    /**
     * Test attribute "file_url_source"
     */
    public function testPropertyFileUrlSource()
    {
    }

    /**
     * Test attribute "file_url_target"
     */
    public function testPropertyFileUrlTarget()
    {
    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {
    }

    /**
     * Test attribute "review"
     */
    public function testPropertyReview()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "text_type"
     */
    public function testPropertyTextType()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
